[package]
name = "VRCJoinNotificator"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
quanta = "0.12.3"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
]
